"""init schema
Revision ID: 61a6d08dd909
Revises: 
Create Date: 2025-09-15 10:32:01.421093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a6d08dd909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clase_nombre'), 'clase', ['nombre'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('atributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('requerido', sa.Boolean(), nullable=False),
    sa.Column('clase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origen_id', sa.Integer(), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ONE_TO_ONE', 'ONE_TO_MANY', 'MANY_TO_MANY', name='reltype'), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['clase.id'], ),
    sa.ForeignKeyConstraint(['origen_id'], ['clase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relacion')
    op.drop_table('atributo')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_clase_nombre'), table_name='clase')
    op.drop_table('clase')
    # ### end Alembic commands ###
