"""init schema
Revision ID: 6d407302a3c1
Revises: a8f766a503bf
Create Date: 2025-09-16 23:53:50.613013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d407302a3c1'
down_revision = 'a8f766a503bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clase', sa.Column('x_grid', sa.Integer(), server_default='0', nullable=False))
    op.add_column('clase', sa.Column('y_grid', sa.Integer(), server_default='0', nullable=False))
    op.add_column('clase', sa.Column('w_grid', sa.Integer(), server_default='12', nullable=False))
    op.add_column('clase', sa.Column('h_grid', sa.Integer(), server_default='6', nullable=False))
    op.add_column('clase', sa.Column('z_index', sa.Integer(), server_default='0', nullable=False))
    op.add_column('relacion', sa.Column('src_anchor', sa.String(length=8), server_default='right', nullable=False))
    op.add_column('relacion', sa.Column('dst_anchor', sa.String(length=8), server_default='left', nullable=False))
    op.add_column('relacion', sa.Column('src_offset', sa.Integer(), server_default='0', nullable=False))
    op.add_column('relacion', sa.Column('dst_offset', sa.Integer(), server_default='0', nullable=False))
    op.add_column('relacion', sa.Column('src_lane', sa.Integer(), server_default='0', nullable=False))
    op.add_column('relacion', sa.Column('dst_lane', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relacion', 'dst_lane')
    op.drop_column('relacion', 'src_lane')
    op.drop_column('relacion', 'dst_offset')
    op.drop_column('relacion', 'src_offset')
    op.drop_column('relacion', 'dst_anchor')
    op.drop_column('relacion', 'src_anchor')
    op.drop_column('clase', 'z_index')
    op.drop_column('clase', 'h_grid')
    op.drop_column('clase', 'w_grid')
    op.drop_column('clase', 'y_grid')
    op.drop_column('clase', 'x_grid')
    # ### end Alembic commands ###
